# Generated by Django 3.2.9 on 2022-10-15 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gpg", "0040_remove_jobordergeneral_updated_by"),
        ("authentication", "0014_alter_client_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveJobOrderApn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ticket_number", models.CharField(blank=True, max_length=100)),
                ("client_file", models.TextField(blank=True)),
                ("client_email", models.EmailField(blank=True, max_length=254)),
                ("staff_email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("na", "N/A"),
                            ("job_order_request", "Job order request"),
                            ("va_processing", "VA Processing"),
                            ("management_processing", "Management Processing"),
                            ("verified_job_order", "Verified Job Order"),
                            ("on_hold", "On Hold"),
                            ("canceled", "Canceled"),
                            ("follow_up", "Follow up"),
                            ("dispute", "Dispute"),
                            ("complete", "Complete"),
                            ("closed", "Closed"),
                            ("under_quality_review", "Under Quality Review"),
                            ("daily_tasks", "Daily Tasks"),
                            ("weekly_tasks", "Weekly Tasks"),
                            ("monthly_tasks", "Monthly Tasks"),
                            ("redo", "Redo"),
                            ("pending", "Pending"),
                            ("request_for_posting", "Request for Posting"),
                            ("mark_as_sold_request", "Mark as Sold Request"),
                            ("initial_dd_processing", "Initial DD Processing"),
                            ("initial_dd_complete", "Initial DD Complete"),
                            ("dd_call_out_processing", "DD Call Out Processing"),
                            ("dd_call_out_complete", "DD Call Out Complete"),
                            ("duplicate_request", "Duplicate Request"),
                            ("multiple_task", "Multiple Task"),
                            ("va_assigned_multiple_task", "VA assigned Multiple Task"),
                            (
                                "va_processing_multiple_task",
                                "VA processing Multiple Task",
                            ),
                            ("va_complete_multiple_task", "VA Complete Multiple Task"),
                            (
                                "for_quality_review_multiple_task",
                                "For Quality Review Multiple Task",
                            ),
                        ],
                        default="na",
                        max_length=100,
                    ),
                ),
                ("due_date", models.DateField()),
                ("date_completed", models.DateField(blank=True, null=True)),
                ("job_description", models.TextField()),
                ("url_of_the_completed_jo", models.TextField(blank=True)),
                ("notes_va", models.TextField(blank=True)),
                ("notes_management", models.TextField(blank=True)),
                (
                    "total_time_consumed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_job_order_categories",
                        to="gpg.categorytype",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_job_order_apn_clients",
                        to="authentication.client",
                    ),
                ),
                (
                    "deadline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_job_order_deadline",
                        to="gpg.deadline",
                    ),
                ),
                (
                    "property_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_property_details",
                        to="gpg.propertydetail",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="archive_job_order_apn_staffs",
                        to="authentication.Staff",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArchiveJobOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_file", models.TextField(blank=True)),
                ("client_email", models.EmailField(blank=True, max_length=254)),
                ("staff_email", models.TextField(blank=True)),
                ("ticket_number", models.CharField(blank=True, max_length=100)),
                ("request_date", models.DateField()),
                ("due_date", models.DateField()),
                ("job_title", models.CharField(max_length=250)),
                ("job_description", models.TextField()),
                ("client_notes", models.TextField(blank=True)),
                ("va_notes", models.TextField(blank=True)),
                ("management_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("na", "N/A"),
                            ("job_order_request", "Job order request"),
                            ("va_processing", "VA Processing"),
                            ("management_processing", "Management Processing"),
                            ("verified_job_order", "Verified Job Order"),
                            ("on_hold", "On Hold"),
                            ("canceled", "Canceled"),
                            ("follow_up", "Follow up"),
                            ("dispute", "Dispute"),
                            ("complete", "Complete"),
                            ("closed", "Closed"),
                            ("under_quality_review", "Under Quality Review"),
                            ("daily_tasks", "Daily Tasks"),
                            ("weekly_tasks", "Weekly Tasks"),
                            ("monthly_tasks", "Monthly Tasks"),
                            ("redo", "Redo"),
                            ("pending", "Pending"),
                            ("request_for_posting", "Request for Posting"),
                            ("mark_as_sold_request", "Mark as Sold Request"),
                            ("initial_dd_processing", "Initial DD Processing"),
                            ("initial_dd_complete", "Initial DD Complete"),
                            ("dd_call_out_processing", "DD Call Out Processing"),
                            ("dd_call_out_complete", "DD Call Out Complete"),
                            ("duplicate_request", "Duplicate Request"),
                            ("multiple_task", "Multiple Task"),
                            ("va_assigned_multiple_task", "VA assigned Multiple Task"),
                            (
                                "va_processing_multiple_task",
                                "VA processing Multiple Task",
                            ),
                            ("va_complete_multiple_task", "VA Complete Multiple Task"),
                            (
                                "for_quality_review_multiple_task",
                                "For Quality Review Multiple Task",
                            ),
                        ],
                        default="na",
                        max_length=100,
                    ),
                ),
                ("date_completed", models.DateField(blank=True, null=True)),
                (
                    "total_time_consumed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("url_of_the_completed_jo", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_job_order_clients",
                        to="authentication.client",
                    ),
                ),
                (
                    "va_assigned",
                    models.ManyToManyField(
                        blank=True,
                        related_name="archive_job_orders_va_assigns",
                        to="authentication.Staff",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
