# Generated by Django 3.2.9 on 2023-03-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0002_auto_20230301_1924"),
        ("archive", "0002_auto_20230301_1927"),
    ]

    operations = []
