# Generated by Django 3.1.8 on 2021-05-03 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_staffaccountbalance_staffpaymenthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffpaymenthistory',
            options={'verbose_name_plural': 'Staff payment histories'},
        ),
    ]
