# Generated by Django 3.1.8 on 2021-09-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0006_paymentportal'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='billing_status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
