# Generated by Django 3.1.8 on 2021-11-11 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0009_staffpaymenthistory_company_name'),
        ('timesheet', '0009_auto_20211022_2133'),
    ]

    operations = [
    ]
