# Generated by Django 3.1.8 on 2021-11-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheet", "0010_paymenthistory_client_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenthistory",
            name="payment_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
