# Generated by Django 3.1.8 on 2021-11-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timesheet", "0010_merge_20211111_2126"),
        ("timesheet", "0011_paymenthistory_payment_id"),
    ]

    operations = []
