# Generated by Django 3.2.9 on 2023-03-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timesheet", "0012_auto_20230301_1924"),
        ("timesheet", "0012_merge_20211116_1802"),
    ]

    operations = []
