# Generated by Django 3.1.8 on 2021-10-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsfeed",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="newsfeedcomment",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
