# Generated by Django 3.1.6 on 2021-02-18 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_client_client_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_lead_added', models.DateField()),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('lead_source', models.CharField(max_length=250)),
                ('lead_status', models.CharField(blank=True, choices=[('interested', 'Interested'), ('ask_additional_info', 'Ask for additional info'), ('ask_for_callback', 'Ask for callback'), ('follow_up_call', 'Follow up Call'), ('others', 'Others')], max_length=50)),
                ('date_of_callback', models.DateField()),
                ('time', models.TimeField()),
                ('call_center_rep_notes', models.TextField()),
                ('call_center_reps_id', models.CharField(max_length=100)),
                ('lead_added_by', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingAdDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, choices=[('company_name', 'Company Name'), ('phone', 'Phone'), ('email_ad', 'Email Ad'), ('website_url', 'Website URL')], max_length=30)),
                ('ad_details', models.TextField()),
                ('notes_client_side', models.TextField()),
                ('notes_va_side', models.TextField()),
                ('notes_management_side', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('cash_terms', models.DecimalField(decimal_places=2, max_digits=11)),
                ('finance_terms', models.TextField()),
                ('other_terms', models.TextField()),
                ('notes', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_prices', to='authentication.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apn', models.CharField(max_length=250)),
                ('county', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('status', models.CharField(blank=True, choices=[('sold', 'Sold'), ('available', 'Available'), ('in_escrow', 'In Escrow'), ('in_contract', 'In Contract'), ('ready_to_purchase', 'Ready to Purchase'), ('ready_for_contract', 'Ready for Contract'), ('canceled_transaction', 'Canceled Transaction')], max_length=25)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_properties', to='authentication.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApprovedOfferNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('cash_terms', models.DecimalField(decimal_places=2, max_digits=11)),
                ('finance_terms', models.TextField()),
                ('other_terms', models.TextField()),
                ('notes', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_offer_notes', to='authentication.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
