# Generated by Django 3.1.6 on 2021-03-12 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gpg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(blank=True, max_length=150)),
                ('apn', models.CharField(max_length=250)),
                ('county', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('status', models.CharField(blank=True, choices=[('sold', 'Sold'), ('available', 'Available'), ('in_escrow', 'In Escrow'), ('in_contract', 'In Contract'), ('ready_to_purchase', 'Ready to Purchase'), ('ready_for_contract', 'Ready for Contract'), ('canceled_transaction', 'Canceled Transaction')], max_length=25)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_properties', to='authentication.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='jobordergeneral',
            options={'ordering': ['-ticket_number']},
        ),
        migrations.AlterField(
            model_name='jobordergeneral',
            name='status',
            field=models.CharField(blank=True, choices=[('na', 'N/A'), ('job_order_request', 'Job order request'), ('va_processing', 'VA Processing'), ('management_processing', 'Management Processing'), ('verified_job_order', 'Verified Job Order'), ('on_hold', 'On Hold'), ('canceled', 'Canceled'), ('follow_up', 'Follow up'), ('dispute', 'Dispute'), ('complete', 'Complete')], default='na', max_length=100),
        ),
        migrations.CreateModel(
            name='PropertyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('cash_terms', models.DecimalField(decimal_places=2, max_digits=11)),
                ('finance_terms', models.TextField()),
                ('other_terms', models.TextField()),
                ('notes', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('change', 'Change'), ('active', 'Active')], default='active', max_length=30)),
                ('property_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_prices', to='gpg.propertydetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingAdDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, choices=[('company_name', 'Company Name'), ('phone', 'Phone'), ('email_ad', 'Email Ad'), ('website_url', 'Website URL')], max_length=30)),
                ('ad_details', models.TextField()),
                ('notes_client_side', models.TextField()),
                ('notes_va_side', models.TextField()),
                ('notes_management_side', models.TextField()),
                ('property_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_ads', to='gpg.propertydetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobOrderCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, choices=[('na', 'N/A'), ('job_order_request', 'Job order request'), ('va_processing', 'VA Processing'), ('management_processing', 'Management Processing'), ('verified_job_order', 'Verified Job Order'), ('on_hold', 'On Hold'), ('canceled', 'Canceled'), ('follow_up', 'Follow up'), ('dispute', 'Dispute'), ('complete', 'Complete')], default='na', max_length=100)),
                ('due_date', models.DateField()),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('job_description', models.TextField()),
                ('completed_url_work', models.URLField(blank=True)),
                ('notes_va', models.TextField(blank=True)),
                ('notes_management', models.TextField(blank=True)),
                ('total_time_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_order_categories', to='gpg.categorytype')),
                ('va_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vas_job_orders_by_categories', to='authentication.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentByPropertDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('property_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_detail_comments', to='gpg.propertydetail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
