# Generated by Django 3.1.8 on 2021-04-20 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpg', '0007_auto_20210420_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetailFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.CharField(blank=True, max_length=250)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('property_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_detail_files', to='gpg.propertydetail')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
