# Generated by Django 3.1.8 on 2021-05-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpg', '0017_jobordergeneral_management_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobordergeneral',
            name='client_file',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
