# Generated by Django 3.1.8 on 2021-05-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpg", "0018_jobordergeneral_client_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobordercategory",
            name="client_file",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
