# Generated by Django 3.1.8 on 2021-09-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpg", "0024_auto_20210824_2208"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertydetail",
            name="apn",
            field=models.CharField(max_length=250),
        ),
    ]
