# Generated by Django 3.2.9 on 2021-12-15 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20211111_2146'),
        ('gpg', '0031_jobordergeneralanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrderGeneralRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_order_general_rating_clients', to='authentication.client')),
                ('job_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_general_ratings', to='gpg.jobordergeneral')),
            ],
            options={
                'verbose_name': 'Job Rating',
                'verbose_name_plural': 'Job Ratings',
            },
        ),
        migrations.CreateModel(
            name='JobOrderCategoryRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_order_category_rating_clients', to='authentication.client')),
                ('job_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_category_ratings', to='gpg.jobordergeneral')),
            ],
            options={
                'verbose_name': 'Job Category Rating',
                'verbose_name_plural': 'Job Category Ratings',
                'ordering': ['-created_at'],
            },
        ),
    ]
