# Generated by Django 3.2.9 on 2022-01-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpg", "0036_auto_20220117_1906"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobordercategory",
            name="client_file",
            field=models.TextField(blank=True),
        ),
    ]
