# Generated by Django 3.2.9 on 2022-02-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpg", "0037_alter_jobordercategory_client_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobordergeneral",
            name="staff_email",
            field=models.TextField(blank=True),
        ),
    ]
