# Generated by Django 3.2.9 on 2022-02-07 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gpg', '0038_alter_jobordergeneral_staff_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobordergeneral',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_updated_job_roders', to=settings.AUTH_USER_MODEL),
        ),
    ]
