# Generated by Django 3.2.9 on 2022-02-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpg', '0039_jobordergeneral_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobordergeneral',
            name='updated_by',
        ),
    ]
