# Generated by Django 3.2.9 on 2022-10-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpg", "0041_auto_20221026_2130"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobordercategory",
            name="days_after_due_date",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobordercategory",
            name="days_before_due_date",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobordergeneral",
            name="days_after_due_date",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobordergeneral",
            name="days_before_due_date",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
