# Generated by Django 3.2.9 on 2023-02-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpg", "0044_propertydetail_property_complete_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounterOffer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.CharField(max_length=250)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SellerList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("apn", models.CharField(max_length=250)),
                ("client_code", models.CharField(max_length=250)),
                ("date_lead_added", models.DateField(auto_now_add=True)),
                (
                    "lead_type",
                    models.CharField(
                        blank=True,
                        choices=[("sellers", "Sellers"), ("buyers", "Buyers")],
                        max_length=25,
                    ),
                ),
                ("seller_lead_name", models.CharField(blank=True, max_length=250)),
                ("phone_number", models.CharField(max_length=250)),
                ("email", models.CharField(blank=True, max_length=250)),
                (
                    "lead_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("interested", "Interested"),
                            ("not_interested", "Not Interested"),
                            ("dead_lead", "Dead Lead"),
                            ("do_not_call_list", "Do Not Call List"),
                        ],
                        max_length=50,
                    ),
                ),
                ("seller_asking_price", models.CharField(blank=True, max_length=250)),
                (
                    "total_minutes_consumed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "counter_offer_amount",
                    models.ManyToManyField(
                        blank=True,
                        related_name="seller_counter_offers",
                        to="gpg.CounterOffer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
