# Generated by Django 3.2.9 on 2023-02-04 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_alter_user_designation_category"),
        ("gpg", "0045_counteroffer_sellerlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerlist",
            name="lead_assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="seller_lead_assigned_to",
                to="authentication.staff",
            ),
        ),
        migrations.AddField(
            model_name="sellerlist",
            name="property_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="property_detail_seller_lists",
                to="gpg.propertydetail",
            ),
        ),
    ]
