# Generated by Django 3.2.9 on 2023-02-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpg", "0048_acquisition"),
    ]

    operations = [
        migrations.AddField(
            model_name="acquisition",
            name="client_code",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
