# Generated by Django 3.2.9 on 2023-03-02 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_alter_user_designation_category"),
        ("gpg", "0053_listingfile_listingstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acquisition",
            name="assigned_sales_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_sales_team_acquistion",
                to="authentication.staff",
            ),
        ),
    ]
