# Generated by Django 3.1.8 on 2021-04-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincredential',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
