# Generated by Django 3.1.8 on 2021-04-26 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_auto_20210422_0842"),
        ("account", "0002_auto_20210423_1209"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_name", models.CharField(max_length=250)),
                ("url", models.CharField(max_length=500)),
                ("file_description", models.TextField()),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="client_account_files",
                        to="authentication.client",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="staff_files_assigned",
                        to="authentication.Staff",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
