# Generated by Django 3.2.9 on 2021-12-14 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("task_designation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskdesignation",
            name="assignment",
        ),
        migrations.AddField(
            model_name="assignmentnote",
            name="task_designation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_designation_assignments",
                to="task_designation.taskdesignation",
            ),
        ),
    ]
