# Generated by Django 3.2.9 on 2021-12-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operational_cost", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="netincome",
            name="month_year",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
