# Generated by Django 3.1.8 on 2021-05-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('due_diligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonelineextension',
            name='original_extension_owner',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
