# Generated by Django 3.1.8 on 2021-05-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("due_diligence", "0003_duediligencecallout"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonelineextension",
            name="allocation_office",
            field=models.CharField(
                choices=[("home_based", "Homebased"), ("office_based", "Office based")],
                default="office_based",
                max_length=250,
            ),
        ),
    ]
