# Generated by Django 3.2.9 on 2022-06-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-id"],
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="thread",
            options={
                "ordering": ["-id"],
                "verbose_name": "Thread",
                "verbose_name_plural": "Threads",
            },
        ),
        migrations.AddField(
            model_name="thread",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("closed", "Closed"),
                    ("on_hold", "On Hold"),
                    ("canceled", "Canceled"),
                ],
                default="active",
                max_length=250,
            ),
        ),
    ]
