# Generated by Django 3.1.6 on 2021-02-17 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate_partner_code', models.CharField(blank=True, max_length=250)),
                ('affiliate_partner_name', models.CharField(blank=True, max_length=250)),
                ('pin', models.CharField(max_length=5)),
                ('lead_information', models.TextField(help_text='Where did you hear about our company?')),
                ('customer_id', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company_category',
            field=models.CharField(blank=True, choices=[('gpg_corporation', 'GPG Corporation'), ('land_master', 'Landmaster.us'), ('call_me_ph', 'CallMe.com.ph'), ('psalms_global', 'Psalmsglobal.com'), ('affiliate_partner', 'Affiliate Partner')], max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='designation_category',
            field=models.CharField(blank=True, choices=[('staff', 'Staff'), ('new_client', 'New Client'), ('current_client', 'Current Client'), ('affiliate_partner', 'Affiliate Partner')], max_length=30),
        ),
        migrations.CreateModel(
            name='InternalFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_files', to='authentication.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
