# Generated by Django 3.1.8 on 2021-04-15 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalfiles',
            options={'verbose_name': 'Internal file'},
        ),
    ]
