# Generated by Django 3.1.6 on 2021-02-19 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_client_client_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_of_birth', models.DateField()),
                ('blood_type', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(max_length=250)),
                ('company_id', models.CharField(max_length=50)),
                ('staff_id', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('company_email', models.EmailField(max_length=254)),
                ('start_date_hired', models.DateField()),
                ('date_hired_in_contract', models.DateField(blank=True, null=True)),
                ('base_pay', models.CharField(blank=True, max_length=100)),
                ('hourly_rate', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, choices=[('regular', 'Regular'), ('probitionary', 'Probitionary'), ('inactive', 'Inactive')], default='probitionary', max_length=50)),
                ('category', models.CharField(blank=True, choices=[('office_based', 'Office Based'), ('part_timers', 'Part-timers'), ('home_based', 'Home Based')], default='office_based', max_length=50)),
                ('residential_address', models.TextField()),
                ('tin_number', models.CharField(blank=True, max_length=250)),
                ('sss_number', models.CharField(blank=True, max_length=250)),
                ('pag_ibig_number', models.CharField(blank=True, max_length=250)),
                ('phil_health_number', models.CharField(blank=True, max_length=250)),
                ('emergency_contact_full_name', models.CharField(blank=True, max_length=250)),
                ('relationship', models.CharField(blank=True, max_length=250)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=250)),
                ('mothers_full_name', models.CharField(blank=True, max_length=250)),
                ('mothers_maiden_name', models.CharField(blank=True, max_length=250)),
                ('fathers_full_name', models.CharField(blank=True, max_length=250)),
                ('bank_name', models.CharField(blank=True, max_length=250)),
                ('bank_account_name', models.CharField(blank=True, max_length=250)),
                ('bank_type', models.CharField(blank=True, max_length=250)),
                ('bank_account_number', models.CharField(blank=True, max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternalFilesStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_files', to='authentication.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
