# Generated by Django 3.1.8 on 2021-05-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_client_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="email",
        ),
    ]
