# Generated by Django 3.2.9 on 2022-02-08 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_auto_20211111_2146"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
