# Generated by Django 3.2.9 on 2021-12-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
